version: '3.7'

services:

  rabbitmq:
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672
    deploy:
      resources:
        limits:
          memory: 0.5GB
    networks:
      - curriculum

  mongodb:
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - $PWD/mongo:/data/db
      - $PWD/config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          memory: 0.5GB
    networks:
      - curriculum


  mysqldb:
    restart: always
    # command: --max_allowed_packet=32505856 
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - $PWD/mysql:/var/lib/mysql
      - $PWD/config/mysql/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh:ro
    deploy:
      resources:
        limits:
          memory: 0.5GB
    networks:
      - curriculum

  
  postgresdb:
    restart: always
    ports:
     - 6432:5432
    expose:
      - 5432
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data/pgdata
      - $PWD/config/postgres/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh:ro
      - /var/run/postgresql:/var/run/postgresql
      # - ./config:/etc/postgresql
    # command: >
    #   -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          memory: 0.5GB
    networks:
      - curriculum