version: "3.7"

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: ./env/rabbitmq/.env
  
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file: ./env/mongo/.env

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    env_file: ./env/mysql/.env

  postgresdb:
    container_name: postgresdb
    image: postgres:14.2
    env_file: ./env/postgres/.env
    

networks:
  curriculum:
    name: curriculum
