# FROM mcr.microsoft.com/mssql/server:2017-CU30-ubuntu-18.04
FROM mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
# Create a config directory
WORKDIR /usr/src/app

# Bundle config source
COPY . /usr/src/app

# Grant permissions for to our scripts to be executable
# RUN chmod +x /usr/src/app/entrypoint.sh
# RUN chmod +x /usr/src/app/configure-db.sh

ENTRYPOINT ["./entrypoint.sh"]

# Tail the setup logs to trap the process
CMD ["tail -f /dev/null"]

EXPOSE 1433

HEALTHCHECK --interval=15s CMD /opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD -Q "select 1" && grep -q "MSSQL CONFIG COMPLETE" ./config.log